### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReactElectron#6]
The icon for the following elements are missing in the drop-down menu:

- Coupling Lens (totally missing)
- PiezoElectricObjective (icon place holder)
- Reflector (icon place holder)

![Screen Shot 2019-05-30 at 14 54 56](https://user-images.githubusercontent.com/4050585/58657617-aabe4600-82ec-11e9-941a-3092ae785317.png)

![Screen Shot 2019-05-30 at 14 54 49](https://user-images.githubusercontent.com/4050585/58657612-a85bec00-82ec-11e9-8dce-0f0da7270f31.png)

**Comment by Akramhar** [comment]
This issue should go in the react component, see referenced
