### ISSUE TITLE
Edit Microscope window

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/4DNMicroscopyMetadataToolReactElectron#7]
The Tier level is missing (field is blank)

Tier 3:
AnnotationRef/Description is missing (both from Instrument tab and from MicroscopeBody tab)

**Comment by Akramhar** [comment]
First part should go in the react repo because its a problem with the component, see 1st referenced issue
Second part should go in the model because of how Instrument and MicroscopeBody are merged together in Microscope json model, see 2nd referenced issue
